version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1506
      POSTGRES_DB: ToDoList
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    container_name: todo-container
    ports:
      - "8080:8080"
    environment:
      DB_USER: postgres
      DB_PASSWORD: 1506
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ToDoList
    depends_on:
      - postgres
