// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",                                    // API version (you should update this)
	Host:             "localhost:8080",                         // Your server's host (can be your actual host)
	BasePath:         "/",                                      // Base path for API routes
	Schemes:          []string{"http", "https"},                // Schemes supported (e.g., HTTP or HTTPS)
	Title:            "ToDoList API",                           // Your API title (e.g., the name of your project)
	Description:      "This is the ToDoList API documentation", // Description of your API
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
